import { NextRequest, NextResponse } from "next/server";

function extractVideoId(url: string): string | null {
    const match = url.match(
        /(?:youtube\.com\/(?:watch\?v=|embed\/|shorts\/)|youtu\.be\/)([a-zA-Z0-9_-]{11})/
    );
    return match?.[1] || null;
}

export async function POST(request: NextRequest) {
    try {
        const { url } = (await request.json()) as { url: string };

        if (!url) {
            return NextResponse.json({ error: "URL is required" }, { status: 400 });
        }

        const videoId = extractVideoId(url);
        if (!videoId) {
            return NextResponse.json({ error: "Invalid YouTube URL" }, { status: 400 });
        }

        // Fetch the video page to get available captions
        const pageRes = await fetch(`https://www.youtube.com/watch?v=${videoId}`, {
            headers: {
                "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36",
                "Accept-Language": "en-US,en;q=0.9",
            },
        });

        if (!pageRes.ok) {
            return NextResponse.json({ error: "Failed to fetch video page" }, { status: 502 });
        }

        const html = await pageRes.text();

        // Extract captions URL from the page
        const captionsMatch = html.match(/"captions":\s*(\{[^}]*"playerCaptionsTracklistRenderer"[^]*?\})\s*,\s*"videoDetails"/);
        if (!captionsMatch) {
            return NextResponse.json({ error: "No captions available for this video" }, { status: 404 });
        }

        let captionsData: any;
        try {
            // The match includes nested JSON, extract just the caption tracks
            const trackMatch = html.match(/"captionTracks":\s*(\[[^\]]*\])/);
            if (!trackMatch) {
                return NextResponse.json({ error: "No caption tracks found" }, { status: 404 });
            }
            captionsData = JSON.parse(trackMatch[1]);
        } catch {
            return NextResponse.json({ error: "Failed to parse captions data" }, { status: 500 });
        }

        if (!Array.isArray(captionsData) || captionsData.length === 0) {
            return NextResponse.json({ error: "No captions available" }, { status: 404 });
        }

        // Prefer English, then auto-generated, then first available
        const englishTrack = captionsData.find((t: any) => t.languageCode === "en" && !t.kind) ||
            captionsData.find((t: any) => t.languageCode === "en") ||
            captionsData[0];

        const captionUrl = englishTrack?.baseUrl;
        if (!captionUrl) {
            return NextResponse.json({ error: "No caption URL found" }, { status: 404 });
        }

        // Fetch the caption XML
        const captionRes = await fetch(captionUrl);
        if (!captionRes.ok) {
            return NextResponse.json({ error: "Failed to fetch captions" }, { status: 502 });
        }

        const captionXml = await captionRes.text();

        // Parse XML transcript — extract text from <text> tags
        const textSegments: string[] = [];
        const textRegex = /<text[^>]*>([^<]*)<\/text>/g;
        let match;
        while ((match = textRegex.exec(captionXml)) !== null) {
            const decoded = match[1]
                .replace(/&amp;/g, "&")
                .replace(/&lt;/g, "<")
                .replace(/&gt;/g, ">")
                .replace(/&quot;/g, '"')
                .replace(/&#39;/g, "'")
                .replace(/\n/g, " ")
                .trim();
            if (decoded) textSegments.push(decoded);
        }

        if (textSegments.length === 0) {
            return NextResponse.json({ error: "Empty transcript" }, { status: 404 });
        }

        const transcript = textSegments.join(" ");

        return NextResponse.json({
            transcript: transcript.slice(0, 50000), // Cap at 50K chars
            language: englishTrack.languageCode || "en",
            isAutoGenerated: englishTrack.kind === "asr",
        });
    } catch (error: any) {
        return NextResponse.json(
            { error: error.message || "Transcript extraction failed" },
            { status: 500 }
        );
    }
}
